# Generated by Django 2.2.7 on 2019-11-06 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('joinDate', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=20)),
                ('dateAdmitted', models.DateField()),
                ('discharged', models.BooleanField()),
                ('bloodType', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagementsystem.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('roomNumber', models.IntegerField()),
                ('occupied', models.BooleanField(blank=True, null=True)),
                ('floor', models.IntegerField()),
                ('patientID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagementsystem.patient')),
            ],
        ),
    ]
